#! /bin/csh -f
    #limit coredumpsize 0
    set DIR=/afs/cs.wisc.edu/p/course/cs354-common/public/bin
    set geom = (-geom =-0+0)
    set sim = spim.solaris
    set log


    # $solp is 1 if hostname contains "sol"; it's 0 otherwise.
    if ($?MACHTYPE && $?OSTYPE) then
      if ($MACHTYPE == "sparc" && $OSTYPE == "Solaris" ) then
        # do nothing
      else 
        if ($MACHTYPE == "sparc-sun-solaris" && $OSTYPE == "solaris" ) then
          # do nothing
        else
	  echo "You are currently running on" `hostname` \
		"which is not a solaris machine."
       	  echo "This simulator only runs on solaris machines," \
		"and not on snakes, Macs, etc."
    	  exit -2
        endif
      endif
    else
	echo "You are currently running on" `hostname` \
		"which is not a solaris machine."
	echo "This simulator only runs on solaris machines," \
		"and not on snakes, Macs, etc."
    	exit -2
    endif

top:
    if ($#argv == 0) set argv = a.out
    switch($argv[1])
    case -nox:
	shift argv
	goto top
    case -log:
	set log = -log
	shift argv
	goto top
    case -*:
	echo Unknown flag: $1
	exit -1
    default:
	breaksw
    endsw
    if (! -e $argv[1]) then
	    echo No $argv[1]'?'
	    goto usage
	endif
    endif
    if ($sim == "xspim") then
	$DIR/$sim $log -file $argv[1] -font "-*-courier-medium-r-normal--12-*-75-*"
    else
	if ($log == "") then
	    $DIR/$sim -file $argv[1]
	else
	    $DIR/$sim -file $argv[1] | tee output.log
	endif
    endif
    goto quit

usage:
    set prname = $0
    echo usage: $prname:t '[ filename ]'

quit:
